image: ubuntu:18.04

before_script:
  - apt-get update -qy && apt-get install --no-install-recommends
  - apt-get install -qy git
  - git config user.email $EMAIL_ID
  - git config user.name $GIT_USERNAME
  # - apt-get install -qy snapd
  # - snap install --classic heroku
  - apt-get install -qy curl
  - curl https://cli-assets.heroku.com/install.sh | sh
  - echo -e "machine git.heroku.com\n  login $EMAIL_ID\n  password $HEROKU_API_KEY" >> ~/.netrc
#   - cat ~/.netrc

stages:
#   - test
#   - package
  - deploy-backend
  - deploy-frontend
  - deploy-react-ui

  # api-deploy:
  #   stage: deploy
  #   variables:
  #     HEROKU_APP_NAME: "api-production"
  #     HEROKU_API_KEY: "THIS-IS-AN-EXAMPLE"
  #     HEROKU_APP_GIT_REMOTE_NAME: "api-production"
  #     DESIRED_BRANCH_TO_DEPLOY: "$CI_COMMIT_REF_NAME"
  #   image: python:3.7
  #   script:
  #     # Assumes you start in `/builds/project-0/`
  #     # Install heroku CLI
  #     - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  #     # Configure Heroku CLI
  #     - heroku git:remote --app $HEROKU_APP_NAME
  #     - git remote rename heroku $HEROKU_APP_GIT_REMOTE_NAME
  #     - heroku stack:set container --app $HEROKU_APP_NAME
  #     - git checkout $DESIRED_BRANCH_TO_DEPLOY
  #     # Sets authentication with git for Heroku
  #     - echo -e "machine git.heroku.com\n  login gitlab_ci_cd@example.com\n  password $HEROKU_API_KEY" >> ~/.netrc
  #     - cat ~/.netrc
  #     # Deploy
  #     - git push --force $HEROKU_APP_GIT_REMOTE_NAME $DESIRED_BRANCH_TO_DEPLOY:master


# cache:
#   paths:
#     - .m2/
# variables:
#   MAVEN_OPTS: "-Dmaven.repo.local=/cache"


# maven_test:
#   image: maven:3-jdk-11
#   stage: test
#   tags: 
#     - immersive-runner-cgi
#   script:
#     - mvn clean testdev
#   script:
#     - mvn clean package

heroku_deploy-backend:
  stage: deploy-backend
  # tags:
  #   - heroku-deploy-backend
  script:
    - heroku git:remote --app $HEROKU_APP_BACKEND
    - git remote rename heroku heroku-backend
    - heroku stack:set heroku-18 --app $HEROKU_APP_BACKEND
    # heroku stack:set heroku-18
    # - git remote add heroku-backend https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_BACKEND.git
    - git subtree split --prefix=gist-service/ -b backend-only
    - git push -f heroku-backend backend-only:master
  only:
    - master

heroku_deploy-frontend:
  stage: deploy-frontend
  # tags:
  #   - heroku-deploy-frontend
  script:
    - heroku git:remote --app $HEROKU_APP_FRONTEND
    - git remote rename heroku heroku-frontend
    - heroku stack:set heroku-18 --app $HEROKU_APP_FRONTEND
    # - git remote add heroku-frontend https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_FRONTEND.git
    - git subtree split --prefix=angular-ui/snippet-ui/ -b frontend-only
    - git push -f heroku-frontend frontend-only:master
  only:
    - master

heroku_deploy-react-ui:
  stage: deploy-react-ui
  script:
    - heroku git:remote --app $HEROKU_APP_REACT_UI
    - git remote rename heroku heroku-react-ui
    - heroku stack:set heroku-18 --app $HEROKU_APP_REACT_UI
    # - git remote add heroku-frontend https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_FRONTEND.git
    - git subtree split --prefix=react-ui/user-ui/ -b react-ui-only
    - git push -f heroku-react-ui react-ui-only:master
  only:
    - master
    
  
  
