name: Deploy Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_BACKEND}} #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL_ID}}
          appdir: "gist-service" # <- This will point to the api folder in your project
        env:
          HD_SPRING_DATA_MONGODB_URI: ${{secrets.SPRING_DATA_MONGODB_URI}}
